package bootstrap

import (
	"regexp"
	"strconv"
	"strings"
	"testing"
)

// migrationsFS is declared in migrate_runner.go via go:embed.

func TestMigrationsEmbeddedNonEmpty(t *testing.T) {
	entries, err := migrationsFS.ReadDir("migrations")
	if err != nil {
		t.Fatalf("read embedded migrations: %v", err)
	}
	if len(entries) == 0 {
		t.Fatal("no embedded migration files")
	}
}

func TestMigrationsFileNaming(t *testing.T) {
	nameRe := regexp.MustCompile(`^(\d{6})_[^.]+\.up\.sql$`)
	entries, err := migrationsFS.ReadDir("migrations")
	if err != nil {
		t.Fatalf("read embedded migrations: %v", err)
	}
	last := 0
	for _, e := range entries {
		m := nameRe.FindStringSubmatch(e.Name())
		if m == nil {
			t.Fatalf("migration file %q does not match NNNNNN_name.up.sql", e.Name())
		}
		version, err := strconv.Atoi(m[1])
		if err != nil {
			t.Fatalf("parse version in %q: %v", e.Name(), err)
		}
		if version <= last {
			t.Fatalf("migration versions must strictly increase; %q follows version %d", e.Name(), last)
		}
		last = version
	}
}

func TestBaselineIsRealSchema(t *testing.T) {
	sql, err := migrationsFS.ReadFile("migrations/000001_init.up.sql")
	if err != nil {
		t.Fatalf("read baseline: %v", err)
	}
	s := string(sql)
	// Guards against an accidental placeholder baseline: the real one is
	// generated by cmd/gen-baseline and must contain the core tables.
	for _, table := range []string{"users", "user_auth_sessions", "tickets", "knowledge_docs", "agents"} {
		if !strings.Contains(s, "CREATE TABLE IF NOT EXISTS \""+table+"\"") {
			t.Fatalf("baseline missing CREATE TABLE IF NOT EXISTS %q — is the placeholder still in place?", table)
		}
	}
	if !strings.Contains(s, "CREATE EXTENSION IF NOT EXISTS vector") {
		t.Fatal("baseline missing vector extension")
	}
	if !strings.Contains(s, "servify_weknora_mappings") {
		t.Fatal("baseline missing WeKnora compatibility tables")
	}
	if !strings.Contains(s, "ivfflat") {
		t.Fatal("baseline missing ivfflat vector index")
	}
}

// TestMigrationsNoConcurrently enforces that no migration uses CREATE INDEX
// CONCURRENTLY: golang-migrate runs each migration inside a transaction where
// concurrent index builds are not allowed.
func TestMigrationsNoConcurrently(t *testing.T) {
	concurrentlyRe := regexp.MustCompile(`(?i)CREATE\s+(UNIQUE\s+)?INDEX\s+CONCURRENTLY`)
	entries, err := migrationsFS.ReadDir("migrations")
	if err != nil {
		t.Fatalf("read embedded migrations: %v", err)
	}
	for _, e := range entries {
		sql, err := migrationsFS.ReadFile("migrations/" + e.Name())
		if err != nil {
			t.Fatalf("read %s: %v", e.Name(), err)
		}
		if concurrentlyRe.MatchString(string(sql)) {
			t.Fatalf("%s uses CREATE INDEX CONCURRENTLY, which cannot run inside a migration transaction", e.Name())
		}
	}
}

func TestResolveSchemaMode(t *testing.T) {
	tests := []struct {
		name           string
		driver         string
		migrationsEnv  string
		autoMigrateEnv string
		want           SchemaManagementMode
	}{
		{"postgres default", "postgres", "", "", SchemaModeVersioned},
		{"postgres unset driver", "", "", "", SchemaModeVersioned},
		{"postgres escape hatch", "postgres", "", "1", SchemaModeAutoMigrate},
		{"postgres escape hatch off", "postgres", "", "0", SchemaModeVersioned},
		{"sqlite keeps automigrate", "sqlite", "", "", SchemaModeAutoMigrate},
		{"migrations off wins", "postgres", "false", "1", SchemaModeSkip},
		{"migrations off explicit", "postgres", "0", "", SchemaModeSkip},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Setenv("MIGRATIONS_ENABLED", tt.migrationsEnv)
			t.Setenv("SERVIFY_AUTO_MIGRATE", tt.autoMigrateEnv)
			if got := ResolveSchemaMode(tt.driver); got != tt.want {
				t.Fatalf("ResolveSchemaMode(%q) with MIGRATIONS_ENABLED=%q SERVIFY_AUTO_MIGRATE=%q = %v, want %v",
					tt.driver, tt.migrationsEnv, tt.autoMigrateEnv, got, tt.want)
			}
		})
	}
}

func TestUsesVersionedMigrations(t *testing.T) {
	for driver, want := range map[string]bool{
		"postgres": true,
		"":         true,
		"SQLite":   false,
		"sqlite3":  false,
	} {
		if got := UsesVersionedMigrations(driver); got != want {
			t.Fatalf("UsesVersionedMigrations(%q) = %v, want %v", driver, got, want)
		}
	}
}
