-- Servify schema baseline (version 1).
--
-- Generated by cmd/gen-baseline (capture logger over a real GORM AutoMigrate
-- against an empty pgvector/pgvector:pg15), then hand-finished. Do not edit
-- table definitions in place: regenerate and re-apply the checklist below.
--   Regenerate:
--     GOTOOLCHAIN=go1.25.7 go -C apps/server run ./cmd/gen-baseline --       -dsn "postgres://postgres:postgres@localhost:55432/servify?sslmode=disable"
--
-- Hand-finishing checklist applied on top of the generated capture:
--   1. CREATE TABLE IF NOT EXISTS everywhere — existing databases no-op, new
--      databases get the full schema.
--   2. The five legacy AutoMigrate AddColumn patches are re-issued as
--      ADD COLUMN IF NOT EXISTS so pre-baseline databases that never ran the
--      patched AutoMigrate still converge.
--   3. The non-GORM WeKnora compatibility tables, seed rows and the
--      updated_at trigger from scripts/init-db.sql are included.
--   4. The ivfflat vector index is included (no CONCURRENTLY: golang-migrate
--      runs each migration in one transaction).
--   5. Up only; no down migration. The baseline is not reversible — roll
--      back by restoring a backup.
-- Unlike the old AutoMigrate path this baseline does not reconcile type
-- drift, missing UNIQUE constraints or removed columns on existing tables;
-- later migrations (000002+) are hand-written for those.

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE TABLE IF NOT EXISTS "users" ("id" bigserial,"username" text NOT NULL,"email" text NOT NULL,"password" text NOT NULL,"name" text,"phone" text,"avatar" text,"role" text DEFAULT 'customer',"status" text DEFAULT 'active',"last_login" timestamptz,"token_valid_after" timestamptz,"token_version" bigint DEFAULT 0,"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,PRIMARY KEY ("id"),CONSTRAINT "uni_users_username" UNIQUE ("username"),CONSTRAINT "uni_users_email" UNIQUE ("email"));
CREATE INDEX IF NOT EXISTS "idx_users_deleted_at" ON "users" ("deleted_at");
CREATE TABLE IF NOT EXISTS "user_auth_sessions" ("id" varchar(64),"user_id" bigint NOT NULL,"status" text DEFAULT 'active',"token_version" bigint DEFAULT 0,"device_fingerprint" varchar(128),"user_agent" varchar(512),"client_ip" varchar(128),"last_seen_at" timestamptz,"last_refreshed_at" timestamptz,"revoked_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_user_auth_sessions_user_id" ON "user_auth_sessions" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_user_auth_sessions_deleted_at" ON "user_auth_sessions" ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_user_auth_sessions_device_fingerprint" ON "user_auth_sessions" ("device_fingerprint");
CREATE INDEX IF NOT EXISTS "idx_user_auth_sessions_status" ON "user_auth_sessions" ("status");
CREATE TABLE IF NOT EXISTS "revoked_tokens" ("id" bigserial,"jti" varchar(128) NOT NULL,"user_id" bigint,"session_id" text,"token_use" text,"reason" text,"expires_at" timestamptz,"revoked_at" timestamptz NOT NULL,"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_revoked_tokens_deleted_at" ON "revoked_tokens" ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_revoked_tokens_revoked_at" ON "revoked_tokens" ("revoked_at");
CREATE INDEX IF NOT EXISTS "idx_revoked_tokens_expires_at" ON "revoked_tokens" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_revoked_tokens_token_use" ON "revoked_tokens" ("token_use");
CREATE INDEX IF NOT EXISTS "idx_revoked_tokens_session_id" ON "revoked_tokens" ("session_id");
CREATE INDEX IF NOT EXISTS "idx_revoked_tokens_user_id" ON "revoked_tokens" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_revoked_tokens_jti" ON "revoked_tokens" ("jti");
CREATE TABLE IF NOT EXISTS "customers" ("id" bigserial,"tenant_id" text,"workspace_id" text,"user_id" bigint,"company" text,"industry" text,"source" text,"tags" text,"notes" text,"priority" text DEFAULT 'normal',"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_customers_deleted_at" ON "customers" ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_customers_user_id" ON "customers" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_customers_scope" ON "customers" ("tenant_id","workspace_id");
CREATE TABLE IF NOT EXISTS "agents" ("id" bigserial,"tenant_id" text,"workspace_id" text,"user_id" bigint,"department" text,"skills" text,"status" text DEFAULT 'offline',"max_concurrent" bigint DEFAULT 5,"current_load" bigint DEFAULT 0,"rating" decimal DEFAULT 5,"total_tickets" bigint DEFAULT 0,"avg_response_time" bigint DEFAULT 0,"last_activity_at" timestamptz,"connected_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_agents_deleted_at" ON "agents" ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_agents_user_id" ON "agents" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_agents_scope" ON "agents" ("tenant_id","workspace_id");
CREATE TABLE IF NOT EXISTS "tickets" ("id" bigserial,"tenant_id" text,"workspace_id" text,"title" text NOT NULL,"description" text,"customer_id" bigint,"agent_id" bigint,"session_id" text,"category" text,"priority" text DEFAULT 'normal',"status" text DEFAULT 'open',"source" text,"tags" text,"due_date" timestamptz,"resolved_at" timestamptz,"closed_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_tickets_deleted_at" ON "tickets" ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_tickets_session_id" ON "tickets" ("session_id");
CREATE INDEX IF NOT EXISTS "idx_tickets_agent_id" ON "tickets" ("agent_id");
CREATE INDEX IF NOT EXISTS "idx_tickets_customer_id" ON "tickets" ("customer_id");
CREATE INDEX IF NOT EXISTS "idx_tickets_scope" ON "tickets" ("tenant_id","workspace_id");
CREATE TABLE IF NOT EXISTS "sessions" ("id" text,"tenant_id" text,"workspace_id" text,"user_id" bigint,"agent_id" bigint,"ticket_id" bigint,"status" text DEFAULT 'active',"platform" text,"started_at" timestamptz,"ended_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_sessions_ticket_id" ON "sessions" ("ticket_id");
CREATE INDEX IF NOT EXISTS "idx_sessions_agent_id" ON "sessions" ("agent_id");
CREATE INDEX IF NOT EXISTS "idx_sessions_user_id" ON "sessions" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_sessions_scope" ON "sessions" ("tenant_id","workspace_id");
CREATE TABLE IF NOT EXISTS "messages" ("id" bigserial,"tenant_id" text,"workspace_id" text,"session_id" text,"user_id" bigint,"content" text,"type" text,"sender" text,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_messages_session_id" ON "messages" ("session_id");
CREATE INDEX IF NOT EXISTS "idx_messages_scope" ON "messages" ("tenant_id","workspace_id");
CREATE INDEX IF NOT EXISTS "idx_messages_user_id" ON "messages" ("user_id");
CREATE TABLE IF NOT EXISTS "transfer_records" ("id" bigserial,"tenant_id" text,"workspace_id" text,"session_id" text,"from_agent_id" bigint,"to_agent_id" bigint,"reason" text,"notes" text,"session_summary" text,"transferred_at" timestamptz,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_transfer_records_session_id" ON "transfer_records" ("session_id");
CREATE INDEX IF NOT EXISTS "idx_transfer_records_scope" ON "transfer_records" ("tenant_id","workspace_id");
CREATE INDEX IF NOT EXISTS "idx_transfer_records_to_agent_id" ON "transfer_records" ("to_agent_id");
CREATE INDEX IF NOT EXISTS "idx_transfer_records_from_agent_id" ON "transfer_records" ("from_agent_id");
CREATE TABLE IF NOT EXISTS "waiting_records" ("id" bigserial,"tenant_id" text,"workspace_id" text,"session_id" text,"reason" text,"target_skills" text,"priority" text,"notes" text,"status" text DEFAULT 'waiting',"queued_at" timestamptz,"assigned_at" timestamptz,"assigned_to" bigint,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_waiting_records_session_id" ON "waiting_records" ("session_id");
CREATE INDEX IF NOT EXISTS "idx_waiting_records_scope" ON "waiting_records" ("tenant_id","workspace_id");
CREATE INDEX IF NOT EXISTS "idx_waiting_records_assigned_to" ON "waiting_records" ("assigned_to");
CREATE TABLE IF NOT EXISTS "ticket_comments" ("id" bigserial,"ticket_id" bigint,"user_id" bigint,"content" text NOT NULL,"type" text DEFAULT 'comment',"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ticket_comments_user_id" ON "ticket_comments" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_ticket_comments_ticket_id" ON "ticket_comments" ("ticket_id");
CREATE TABLE IF NOT EXISTS "ticket_files" ("id" bigserial,"ticket_id" bigint,"user_id" bigint,"file_name" text NOT NULL,"file_path" text NOT NULL,"file_size" bigint,"mime_type" text,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ticket_files_user_id" ON "ticket_files" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_ticket_files_ticket_id" ON "ticket_files" ("ticket_id");
CREATE TABLE IF NOT EXISTS "ticket_statuses" ("id" bigserial,"ticket_id" bigint,"user_id" bigint,"from_status" text,"to_status" text,"reason" text,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ticket_statuses_user_id" ON "ticket_statuses" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_ticket_statuses_ticket_id" ON "ticket_statuses" ("ticket_id");
CREATE TABLE IF NOT EXISTS "custom_fields" ("id" bigserial,"tenant_id" text,"workspace_id" text,"resource" text DEFAULT 'ticket',"key" text NOT NULL,"name" text NOT NULL,"type" text NOT NULL,"required" boolean DEFAULT false,"active" boolean DEFAULT true,"options_json" text,"validation_json" text,"show_when_json" text,"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,PRIMARY KEY ("id"),CONSTRAINT "uni_custom_fields_key" UNIQUE ("key"));
CREATE INDEX IF NOT EXISTS "idx_custom_fields_resource" ON "custom_fields" ("resource");
CREATE INDEX IF NOT EXISTS "idx_custom_fields_workspace_id" ON "custom_fields" ("workspace_id");
CREATE INDEX IF NOT EXISTS "idx_custom_fields_tenant_id" ON "custom_fields" ("tenant_id");
CREATE INDEX IF NOT EXISTS "idx_custom_fields_deleted_at" ON "custom_fields" ("deleted_at");
CREATE TABLE IF NOT EXISTS "ticket_custom_field_values" ("id" bigserial,"ticket_id" bigint,"custom_field_id" bigint,"value" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ticket_custom_field_values_custom_field_id" ON "ticket_custom_field_values" ("custom_field_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uniq_ticket_field" ON "ticket_custom_field_values" ("ticket_id","custom_field_id");
CREATE INDEX IF NOT EXISTS "idx_ticket_custom_field_values_ticket_id" ON "ticket_custom_field_values" ("ticket_id");
CREATE TABLE IF NOT EXISTS "knowledge_docs" ("id" bigserial,"tenant_id" text,"workspace_id" text,"provider_id" text,"external_id" text,"title" text,"content" text,"category" text,"tags" text,"is_public" boolean DEFAULT false,"embedding" vector(1536),"chunk_index" bigint DEFAULT 0,"doc_chunk_id" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_knowledge_docs_doc_chunk_id" ON "knowledge_docs" ("doc_chunk_id");
CREATE INDEX IF NOT EXISTS "idx_knowledge_docs_is_public" ON "knowledge_docs" ("is_public");
CREATE INDEX IF NOT EXISTS "idx_knowledge_docs_external_id" ON "knowledge_docs" ("external_id");
CREATE INDEX IF NOT EXISTS "idx_knowledge_docs_provider_id" ON "knowledge_docs" ("provider_id");
CREATE INDEX IF NOT EXISTS "idx_knowledge_docs_workspace_id" ON "knowledge_docs" ("workspace_id");
CREATE INDEX IF NOT EXISTS "idx_knowledge_docs_tenant_id" ON "knowledge_docs" ("tenant_id");
CREATE TABLE IF NOT EXISTS "knowledge_index_jobs" ("id" text,"document_id" bigint NOT NULL,"status" text NOT NULL,"error" text,"created_at" timestamptz,"updated_at" timestamptz,"completed_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_knowledge_index_jobs_status" ON "knowledge_index_jobs" ("status");
CREATE INDEX IF NOT EXISTS "idx_knowledge_index_jobs_document_id" ON "knowledge_index_jobs" ("document_id");
CREATE TABLE IF NOT EXISTS "web_rtc_connections" ("id" text,"session_id" text,"status" text DEFAULT 'connecting',"connection_type" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_web_rtc_connections_session_id" ON "web_rtc_connections" ("session_id");
CREATE TABLE IF NOT EXISTS "daily_stats" ("id" bigserial,"date" timestamptz,"total_sessions" bigint DEFAULT 0,"total_messages" bigint DEFAULT 0,"total_tickets" bigint DEFAULT 0,"resolved_tickets" bigint DEFAULT 0,"avg_response_time" bigint DEFAULT 0,"avg_resolution_time" bigint DEFAULT 0,"customer_satisfaction" decimal DEFAULT 0,"ai_usage_count" bigint DEFAULT 0,"we_knora_usage_count" bigint DEFAULT 0,"sla_violations" bigint DEFAULT 0,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_daily_stats_date" ON "daily_stats" ("date");
CREATE TABLE IF NOT EXISTS "sla_configs" ("id" bigserial,"tenant_id" text,"workspace_id" text,"name" text NOT NULL,"priority" text NOT NULL,"customer_tier" text DEFAULT '',"tags" text,"warning_threshold" bigint DEFAULT 80,"first_response_time" bigint NOT NULL,"resolution_time" bigint NOT NULL,"escalation_time" bigint NOT NULL,"business_hours_only" boolean DEFAULT false,"active" boolean DEFAULT true,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"),CONSTRAINT "uni_sla_configs_name" UNIQUE ("name"));
CREATE INDEX IF NOT EXISTS "idx_sla_configs_tenant_id" ON "sla_configs" ("tenant_id");
CREATE INDEX IF NOT EXISTS "idx_sla_configs_workspace_id" ON "sla_configs" ("workspace_id");
CREATE TABLE IF NOT EXISTS "sla_violations" ("id" bigserial,"tenant_id" text,"workspace_id" text,"ticket_id" bigint,"sla_config_id" bigint,"violation_type" text NOT NULL,"deadline" timestamptz,"violated_at" timestamptz,"resolved_at" timestamptz,"resolved" boolean DEFAULT false,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_sla_violations_sla_config_id" ON "sla_violations" ("sla_config_id");
CREATE INDEX IF NOT EXISTS "idx_sla_violations_ticket_id" ON "sla_violations" ("ticket_id");
CREATE INDEX IF NOT EXISTS "idx_sla_violations_workspace_id" ON "sla_violations" ("workspace_id");
CREATE INDEX IF NOT EXISTS "idx_sla_violations_tenant_id" ON "sla_violations" ("tenant_id");
CREATE TABLE IF NOT EXISTS "customer_satisfactions" ("id" bigserial,"tenant_id" text,"workspace_id" text,"ticket_id" bigint,"customer_id" bigint,"agent_id" bigint,"rating" bigint NOT NULL,"comment" text,"category" text,"created_at" timestamptz,PRIMARY KEY ("id"),CONSTRAINT "chk_customer_satisfactions_rating" CHECK (rating >= 1 AND rating <= 5));
CREATE INDEX IF NOT EXISTS "idx_customer_satisfactions_agent_id" ON "customer_satisfactions" ("agent_id");
CREATE INDEX IF NOT EXISTS "idx_customer_satisfactions_customer_id" ON "customer_satisfactions" ("customer_id");
CREATE INDEX IF NOT EXISTS "idx_customer_satisfactions_ticket_id" ON "customer_satisfactions" ("ticket_id");
CREATE INDEX IF NOT EXISTS "idx_customer_satisfactions_workspace_id" ON "customer_satisfactions" ("workspace_id");
CREATE INDEX IF NOT EXISTS "idx_customer_satisfactions_tenant_id" ON "customer_satisfactions" ("tenant_id");
CREATE TABLE IF NOT EXISTS "satisfaction_surveys" ("id" bigserial,"tenant_id" text,"workspace_id" text,"ticket_id" bigint,"customer_id" bigint,"agent_id" bigint,"channel" text DEFAULT 'email',"status" text DEFAULT 'queued',"survey_token" text,"sent_at" timestamptz,"expires_at" timestamptz,"completed_at" timestamptz,"satisfaction_id" bigint,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_satisfaction_surveys_workspace_id" ON "satisfaction_surveys" ("workspace_id");
CREATE INDEX IF NOT EXISTS "idx_satisfaction_surveys_tenant_id" ON "satisfaction_surveys" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_satisfaction_surveys_survey_token" ON "satisfaction_surveys" ("survey_token");
CREATE INDEX IF NOT EXISTS "idx_satisfaction_surveys_status" ON "satisfaction_surveys" ("status");
CREATE INDEX IF NOT EXISTS "idx_satisfaction_surveys_agent_id" ON "satisfaction_surveys" ("agent_id");
CREATE INDEX IF NOT EXISTS "idx_satisfaction_surveys_customer_id" ON "satisfaction_surveys" ("customer_id");
CREATE INDEX IF NOT EXISTS "idx_satisfaction_surveys_ticket_id" ON "satisfaction_surveys" ("ticket_id");
CREATE TABLE IF NOT EXISTS "app_integrations" ("id" bigserial,"tenant_id" text,"workspace_id" text,"name" text NOT NULL,"slug" text NOT NULL,"vendor" text,"category" text,"summary" text,"icon_url" text,"capabilities" text,"config_schema" text,"i_frame_url" text,"enabled" boolean DEFAULT true,"last_sync_status" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"),CONSTRAINT "uni_app_integrations_name" UNIQUE ("name"),CONSTRAINT "uni_app_integrations_slug" UNIQUE ("slug"));
CREATE INDEX IF NOT EXISTS "idx_app_integrations_tenant_id" ON "app_integrations" ("tenant_id");
CREATE INDEX IF NOT EXISTS "idx_app_integrations_workspace_id" ON "app_integrations" ("workspace_id");
CREATE TABLE IF NOT EXISTS "shift_schedules" ("id" bigserial,"tenant_id" text,"workspace_id" text,"agent_id" bigint,"shift_type" text NOT NULL,"start_time" timestamptz NOT NULL,"end_time" timestamptz NOT NULL,"date" timestamptz,"status" text DEFAULT 'scheduled',"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_shift_schedules_agent_id" ON "shift_schedules" ("agent_id");
CREATE INDEX IF NOT EXISTS "idx_shift_schedules_workspace_id" ON "shift_schedules" ("workspace_id");
CREATE INDEX IF NOT EXISTS "idx_shift_schedules_tenant_id" ON "shift_schedules" ("tenant_id");
CREATE INDEX IF NOT EXISTS "idx_shift_schedules_date" ON "shift_schedules" ("date");
CREATE TABLE IF NOT EXISTS "automation_triggers" ("id" bigserial,"name" text NOT NULL,"event" text NOT NULL,"conditions" text,"actions" text,"active" boolean DEFAULT true,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"),CONSTRAINT "uni_automation_triggers_name" UNIQUE ("name"));
CREATE TABLE IF NOT EXISTS "automation_runs" ("id" bigserial,"trigger_id" bigint,"ticket_id" bigint,"status" text,"message" text,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_automation_runs_status" ON "automation_runs" ("status");
CREATE INDEX IF NOT EXISTS "idx_automation_runs_ticket_id" ON "automation_runs" ("ticket_id");
CREATE INDEX IF NOT EXISTS "idx_automation_runs_trigger_id" ON "automation_runs" ("trigger_id");
CREATE TABLE IF NOT EXISTS "macros" ("id" bigserial,"tenant_id" text,"workspace_id" text,"name" text NOT NULL,"description" text,"language" text DEFAULT 'zh',"content" text,"active" boolean DEFAULT true,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"),CONSTRAINT "uni_macros_name" UNIQUE ("name"));
CREATE INDEX IF NOT EXISTS "idx_macros_workspace_id" ON "macros" ("workspace_id");
CREATE INDEX IF NOT EXISTS "idx_macros_tenant_id" ON "macros" ("tenant_id");
CREATE TABLE IF NOT EXISTS "tenant_configs" ("id" bigserial,"tenant_id" text NOT NULL,"portal_json" text,"open_ai_json" text,"dify_json" text,"we_knora_json" text,"session_risk_json" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_tenant_configs_tenant_id" ON "tenant_configs" ("tenant_id");
CREATE TABLE IF NOT EXISTS "workspace_configs" ("id" bigserial,"tenant_id" text NOT NULL,"workspace_id" text NOT NULL,"portal_json" text,"open_ai_json" text,"dify_json" text,"we_knora_json" text,"session_risk_json" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_workspace_configs_scope" ON "workspace_configs" ("tenant_id","workspace_id");
CREATE TABLE IF NOT EXISTS "audit_logs" ("id" bigserial,"actor_user_id" bigint,"principal_kind" text NOT NULL,"action" text NOT NULL,"resource_type" text NOT NULL,"resource_id" text,"route" text NOT NULL,"method" text NOT NULL,"status_code" bigint,"success" boolean,"request_id" text,"client_ip" text,"user_agent" text,"tenant_id" text,"workspace_id" text,"request_json" text,"before_json" text,"after_json" text,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_audit_logs_action" ON "audit_logs" ("action");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_actor_user_id" ON "audit_logs" ("actor_user_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_workspace_id" ON "audit_logs" ("workspace_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_resource_id" ON "audit_logs" ("resource_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_resource_type" ON "audit_logs" ("resource_type");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_principal_kind" ON "audit_logs" ("principal_kind");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_tenant_id" ON "audit_logs" ("tenant_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_request_id" ON "audit_logs" ("request_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_success" ON "audit_logs" ("success");
CREATE TABLE IF NOT EXISTS "voice_calls" ("id" text,"session_id" text,"status" text DEFAULT 'started',"started_at" timestamptz,"answered_at" timestamptz,"held_at" timestamptz,"resumed_at" timestamptz,"ended_at" timestamptz,"transfer_to_agent" bigint,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_voice_calls_session_id" ON "voice_calls" ("session_id");
CREATE TABLE IF NOT EXISTS "voice_recordings" ("id" text,"call_id" text,"provider" text,"status" text DEFAULT 'recording',"storage_uri" text,"started_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_voice_recordings_call_id" ON "voice_recordings" ("call_id");
CREATE TABLE IF NOT EXISTS "voice_transcripts" ("id" bigserial,"call_id" text,"content" text,"language" text,"finalized" boolean DEFAULT false,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_voice_transcripts_call_id" ON "voice_transcripts" ("call_id");
-- ---------------------------------------------------------------------------
-- Legacy AutoMigrate AddColumn patches (see checklist item 2)
-- ---------------------------------------------------------------------------
ALTER TABLE knowledge_docs ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false;
ALTER TABLE knowledge_docs ADD COLUMN IF NOT EXISTS provider_id text;
ALTER TABLE knowledge_docs ADD COLUMN IF NOT EXISTS external_id text;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS last_activity_at timestamptz;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS connected_at timestamptz;

-- ---------------------------------------------------------------------------
-- Runtime composite indexes (formerly bootstrap.CreateIndexes)
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_messages_session_created ON messages(session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_tickets_status_created ON tickets(status, created_at);
CREATE INDEX IF NOT EXISTS idx_tickets_agent_status ON tickets(agent_id, status);
CREATE INDEX IF NOT EXISTS idx_tickets_customer_created ON tickets(customer_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sessions_user_created ON sessions(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_user_auth_sessions_user_status ON user_auth_sessions(user_id, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_revoked_tokens_jti_revoked ON revoked_tokens(jti, revoked_at);
CREATE INDEX IF NOT EXISTS idx_revoked_tokens_expires_at ON revoked_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_sessions_agent_status ON sessions(agent_id, status);
CREATE INDEX IF NOT EXISTS idx_customers_priority ON customers(priority);
CREATE INDEX IF NOT EXISTS idx_customers_source ON customers(source);
CREATE INDEX IF NOT EXISTS idx_customers_industry ON customers(industry);
CREATE INDEX IF NOT EXISTS idx_agents_status ON agents(status);
CREATE INDEX IF NOT EXISTS idx_agents_department ON agents(department);
CREATE INDEX IF NOT EXISTS idx_daily_stats_date ON daily_stats(date);
-- ---------------------------------------------------------------------------
-- pgvector semantic search support (formerly scripts/init-db.sql)
-- The embedding / chunk_index / doc_chunk_id columns are part of the
-- knowledge_docs table definition above; existing databases get them via the
-- patch section only if missing.
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_knowledge_docs_embedding
ON knowledge_docs
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

COMMENT ON COLUMN knowledge_docs.embedding IS '文档的向量表示，用于语义搜索';
COMMENT ON COLUMN knowledge_docs.chunk_index IS '文档分块索引，同一文档的不同分块有相同 doc_chunk_id';
COMMENT ON COLUMN knowledge_docs.doc_chunk_id IS '文档块 ID，用于标识属于同一文档的不同分块';

-- ---------------------------------------------------------------------------
-- WeKnora compatibility tables (formerly scripts/init-db.sql)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS servify_weknora_mappings (
    id SERIAL PRIMARY KEY,
    servify_doc_id INTEGER,
    weknora_doc_id VARCHAR(255) NOT NULL,
    weknora_kb_id VARCHAR(255) NOT NULL,
    mapping_type VARCHAR(50) DEFAULT 'document',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(servify_doc_id, weknora_doc_id)
);

CREATE INDEX IF NOT EXISTS idx_mappings_servify_doc ON servify_weknora_mappings(servify_doc_id);
CREATE INDEX IF NOT EXISTS idx_mappings_weknora_doc ON servify_weknora_mappings(weknora_doc_id);
CREATE INDEX IF NOT EXISTS idx_mappings_kb ON servify_weknora_mappings(weknora_kb_id);

CREATE TABLE IF NOT EXISTS ai_service_metrics (
    id SERIAL PRIMARY KEY,
    service_type VARCHAR(50) NOT NULL, -- compatibility values include 'weknora', plus 'fallback' and 'openai'
    query_count BIGINT DEFAULT 0,
    success_count BIGINT DEFAULT 0,
    error_count BIGINT DEFAULT 0,
    avg_latency_ms INTEGER DEFAULT 0,
    last_updated TIMESTAMP DEFAULT NOW(),
    date DATE DEFAULT CURRENT_DATE,
    UNIQUE(service_type, date)
);

CREATE TABLE IF NOT EXISTS knowledge_sync_logs (
    id SERIAL PRIMARY KEY,
    operation VARCHAR(50) NOT NULL, -- 'upload', 'update', 'delete'
    document_id VARCHAR(255),
    servify_doc_id INTEGER,
    weknora_doc_id VARCHAR(255),
    status VARCHAR(50) NOT NULL, -- 'pending', 'success', 'failed'
    error_message TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    completed_at TIMESTAMP
);

INSERT INTO ai_service_metrics (service_type, date)
VALUES
    ('weknora', CURRENT_DATE),
    ('fallback', CURRENT_DATE),
    ('openai', CURRENT_DATE)
ON CONFLICT (service_type, date) DO NOTHING;

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE OR REPLACE TRIGGER update_mappings_updated_at
    BEFORE UPDATE ON servify_weknora_mappings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
